import type { Block, SpecialKind } from './types'

// Sprite-sheet based — generated by scripts/build-sprites.mjs (128px cell, mobile-first)
// Sheets are in public/sprites/ served at BASE_URL + sprites/
const TILE_SHEET = `${import.meta.env.BASE_URL}sprites/tiles.webp`
const TILE_SHEET_PNG = `${import.meta.env.BASE_URL}sprites/tiles.png`
const SPECIAL_SHEET = `${import.meta.env.BASE_URL}sprites/specials.webp`
const SPECIAL_SHEET_PNG = `${import.meta.env.BASE_URL}sprites/specials.png`

import titleImg from '../assets/tilemama_cropped.png'
import rainbowFallback from '../assets/speciali/rainbow_nobg_cropped.png'

// Map from manifest (cols/rows based, percentage responsive — mobile-first)
const TILE_COLS = 5
const TILE_ROWS = 4
const SPECIAL_COLS = 5
const SPECIAL_ROWS = 2

const tilePos: Record<string, { col: number; row: number }> = {
  'green-1': { col: 0, row: 0 },
  'green-2': { col: 1, row: 0 },
  'green-4': { col: 2, row: 0 },
  'green-8': { col: 3, row: 0 },
  'green-16': { col: 4, row: 0 },
  'yellow-1': { col: 0, row: 1 },
  'yellow-2': { col: 1, row: 1 },
  'yellow-4': { col: 2, row: 1 },
  'yellow-8': { col: 3, row: 1 },
  'yellow-16': { col: 4, row: 1 },
  'red-1': { col: 0, row: 2 },
  'red-2': { col: 1, row: 2 },
  'red-4': { col: 2, row: 2 },
  'red-8': { col: 3, row: 2 },
  'red-16': { col: 4, row: 2 },
  'blue-1': { col: 0, row: 3 },
  'blue-2': { col: 1, row: 3 },
  'blue-4': { col: 2, row: 3 },
  'blue-8': { col: 3, row: 3 },
  'blue-16': { col: 4, row: 3 },
}

const specialPos: Record<string, { col: number; row: number }> = {
  bombColor: { col: 0, row: 0 },
  clone: { col: 1, row: 0 },
  wall: { col: 2, row: 0 },
  'wall-cracked': { col: 3, row: 0 },
  laser: { col: 4, row: 0 },
  jolly: { col: 0, row: 1 },
  shuffle: { col: 1, row: 1 },
  star: { col: 2, row: 1 },
  vortex: { col: 3, row: 1 },
  x2: { col: 4, row: 1 },
}

export function tileSprite(block: Block): string {
  // kept for backwards compat — returns sheet URL (not used for <img> anymore)
  return TILE_SHEET
}

export function specialSprite(kind: SpecialKind, hp?: number): string {
  return SPECIAL_SHEET
}

function pctPos(col: number, row: number, cols: number, rows: number): string {
  const x = cols <= 1 ? '0%' : `${(col * 100) / (cols - 1)}%`
  const y = rows <= 1 ? '0%' : `${(row * 100) / (rows - 1)}%`
  return `${x} ${y}`
}

export function tileSpriteStyle(block: Block): string {
  if (block.jolly) return specialSpriteStyle('jolly')
  const key = `${block.color}-${block.value}`
  const pos = tilePos[key] ?? tilePos[`${block.color}-16`] ?? tilePos['green-1']
  const size = `${TILE_COLS * 100}% ${TILE_ROWS * 100}%`
  const p = pctPos(pos.col, pos.row, TILE_COLS, TILE_ROWS)
  return `background-image:image-set(url(${TILE_SHEET}) type("image/webp"), url(${TILE_SHEET_PNG}) type("image/png"));background-size:${size};background-position:${p};background-repeat:no-repeat;`
}

export function specialSpriteStyle(kind: SpecialKind, hp?: number): string {
  const k = kind === 'wall' && hp === 1 ? 'wall-cracked' : kind
  const pos = specialPos[k] ?? specialPos.star
  const size = `${SPECIAL_COLS * 100}% ${SPECIAL_ROWS * 100}%`
  const p = pctPos(pos.col, pos.row, SPECIAL_COLS, SPECIAL_ROWS)
  return `background-image:image-set(url(${SPECIAL_SHEET}) type("image/webp"), url(${SPECIAL_SHEET_PNG}) type("image/png"));background-size:${size};background-position:${p};background-repeat:no-repeat;`
}

export const titleSprite = titleImg
export const rainbowSprite = rainbowFallback

// Expose sheet constants for preload
export const spriteSheets = { tile: TILE_SHEET, tilePng: TILE_SHEET_PNG, special: SPECIAL_SHEET, specialPng: SPECIAL_SHEET_PNG, tileCols: TILE_COLS, tileRows: TILE_ROWS, specialCols: SPECIAL_COLS, specialRows: SPECIAL_ROWS }
