export const GAME_CONFIG = {
  gridSize: 8,
  initialBlocksPerColor: 4,
  explosionValue: 32,
  explosionSpawnCount: 4,
  starIntervalMs: 10000,
  bonusMinDelayMs: 6500,
  bonusMaxDelayMs: 10500,
  specialDurationMs: 9000,
  wallDurationMs: 12000,
  wallHp: 2,
  virusIntervalMs: 3000,
  cleanupIntervalMs: 250,
  virusTickMs: 1000,
  // achievements / missions
  missionsPerRun: 3,
  missionRewardScore: 80,
  missionRewardCoins: 15,
  missionRewardMultiplier: 1.5,
  missionAllBonusScore: 300,
  missionAllBonusCoins: 50,
  achievementRewardCoins: 30,
  achievementRewardScore: 150,
} as const;
